# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        server_version: 5.7.8
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            User:
                type: xml
                prefix: Domain\User\Model
                dir: '%kernel.root_dir%/../src/Infrastructure/UserBundle/Resources/config/persistence/Model'
                is_bundle: false

            Board:
                type: xml
                prefix: Domain\Board\Model
                dir: '%kernel.root_dir%/../src/Infrastructure/BoardBundle/Resources/config/persistence/Model'
                is_bundle: false

            Game:
                type: xml
                prefix: Domain\Game\Model
                dir: '%kernel.root_dir%/../src/Infrastructure/GameBundle/Resources/config/persistence/Model'
                is_bundle: false