services:
    board.use_case.board_command:
        class: Application\UseCase\Board\BoardCommand
        arguments:
          - '@board.factory.board'
          - '@board.repository.board'

    board.use_case.board_query:
        class: Application\UseCase\Board\BoardQuery
        arguments:
          - '@board.repository.board'