services:
    user.repository.user:
        class: Infrastructure\UserBundle\Repository\UserRepository
        parent: common.repository.abstract
        arguments:
          - Domain\User\Model\User



